network:
  version: 2
  ethernets:
    eno1:
      dhcp4: no
      dhcp6: no
      optional: yes
      addresses:
        - "192.168.20.2/24"
        - "fd00:0:0:20::2/64"
      routes:
        - to: "192.168.10.0/24"
          via: "192.168.20.1"
        - to: "fd00:0:0:10::/64"
          via: "fd00:0:0:20::1"
    ens5:
      dhcp4: no
      dhcp6: no
      optional: yes
      addresses:
        - "192.168.30.1/24"
        - "fd00:0:0:30::1/64"
    usb0:
      dhcp4: yes
      dhcp6: yes
